[2025-05-23, 12:00:25] ERROR - Task failed with exception: source="task"
TypeError: Returned output was type <class 'str'> expected dictionary for multiple_outputs
File "/app/fdi/fdi_venv/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py", line 849 in run

File "/app/fdi/fdi_venv/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py", line 1180 in _push_xcom_if_needed

[2025-05-23, 12:00:25] INFO - Task instance in failure state: chan="stdout": source="task"
[2025-05-23, 12:00:25] INFO - Task start: chan="stdout": source="task"
[2025-05-23, 12:00:25] INFO - Task:<Task(AgentDecoratedOperator): process_document>: chan="stdout": source="task"
[2025-05-23, 12:00:25] INFO - Failure caused by Returned output was type <class 'str'> expected dictionary for multiple_outputs: chan="stdout": source="task"
