Broken DAG: [/app/fdi/dags/dag_check.py] Traceback (most recent call last):
  File "/app/fdi/dags/dag_check.py", line 25, in <module>
    python_task = PythonOperator(
  File "/app/airflow_310_env/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'python_callable'
