Log message source details: sources=["/app/fdi/airflow/logs/dag_id=document_classifier_dag/run_id=manual__2025-05-21T18:21:31.001293+00:00/task_id=classify/map_index=0/attempt=1.log"]
::group::Log message source details: sources=["/app/fdi/airflow/logs/dag_id=document_classifier_dag/run_id=manual__2025-05-21T18:21:31.001293+00:00/task_id=classify/map_index=0/attempt=1.log"]
[2025-05-21, 23:51:32] INFO - DAG bundles loaded: dags-folder, example_dags: source="airflow.dag_processing.bundles.manager.DagBundlesManager"
[2025-05-21, 23:51:32] INFO - Filling up the DagBag from /app/fdi/dags/dyno3.py: source="airflow.models.dagbag.DagBag"
[2025-05-21, 23:51:32] INFO - Running classifier for: /app/fdi/Documents/FRD.pptx: source="airflow.utils.log.logging_mixin.LoggingMixin"
[2025-05-21, 23:51:33] INFO - Task instance is in running state: chan="stdout": source="task"
[2025-05-21, 23:51:33] INFO -  Previous state of the Task instance: TaskInstanceState.QUEUED: chan="stdout": source="task"
[2025-05-21, 23:51:33] INFO - Current task name:classify: chan="stdout": source="task"
[2025-05-21, 23:51:33] INFO - Dag name:document_classifier_dag: chan="stdout": source="task"
[2025-05-21, 23:51:33] INFO - Executing LLM call: chan="stdout": source="task"
Calling tool detect_images_in_document with args {"path":"/app/fdi/Documents/FRD.pptx"}: chan="stdout": source="task"
[2025-05-21, 23:51:34] INFO - Done. Returned value was: AgentRunResult(data='[{"agent": "File Parsing Agent", "path": "/app/fdi/Documents/FRD.pptx"}]'): source="airflow.task.operators.airflow_ai_sdk.operators.agent.AgentDecoratedOperator"
[2025-05-21, 23:51:34] INFO - Prompt: AgentRunResult(data='[{"agent": "File Parsing Agent", "path": "/app/fdi/Documents/FRD.pptx"}]'): chan="stdout": source="task"
[2025-05-21, 23:51:34] INFO - Error: 'AgentRunResult' object is not iterable: chan="stdout": source="task"
[2025-05-21, 23:51:34] ERROR - Task failed with exception: source="task"
TypeError: 'AgentRunResult' object is not iterable
File "/app/fdi/fdi_venv/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py", line 838 in run

File "/app/fdi/fdi_venv/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py", line 1130 in _execute_task

File "/app/fdi/fdi_venv/lib/python3.12/site-packages/airflow/sdk/bases/operator.py", line 408 in wrapper

File "/app/fdi/fdi_venv/lib/python3.12/site-packages/airflow_ai_sdk/operators/agent.py", line 52 in execute

File "/app/fdi/fdi_venv/lib/python3.12/site-packages/airflow_ai_sdk/operators/agent.py", line 48 in execute

File "/app/fdi/fdi_venv/lib/python3.12/site-packages/pydantic_ai/agent.py", line 578 in run_sync

File "/usr/lib/python3.12/asyncio/base_events.py", line 687 in run_until_complete

File "/app/fdi/fdi_venv/lib/python3.12/site-packages/pydantic_ai/agent.py", line 329 in run

File "/app/fdi/fdi_venv/lib/python3.12/site-packages/pydantic_ai/agent.py", line 1454 in __anext__

File "/app/fdi/fdi_venv/lib/python3.12/site-packages/pydantic_graph/graph.py", line 790 in __anext__

File "/app/fdi/fdi_venv/lib/python3.12/site-packages/pydantic_graph/graph.py", line 763 in next

File "/app/fdi/fdi_venv/lib/python3.12/site-packages/pydantic_ai/_agent_graph.py", line 264 in run

File "/app/fdi/fdi_venv/lib/python3.12/site-packages/pydantic_ai/_agent_graph.py", line 317 in _make_request

File "/app/fdi/fdi_venv/lib/python3.12/site-packages/pydantic_ai/models/openai.py", line 193 in request

File "/app/fdi/fdi_venv/lib/python3.12/site-packages/pydantic_ai/models/openai.py", line 262 in _completions_create

File "/app/fdi/fdi_venv/lib/python3.12/site-packages/pydantic_ai/models/openai.py", line 327 in _map_message

File "/app/fdi/fdi_venv/lib/python3.12/site-packages/pydantic_ai/models/openai.py", line 382 in _map_user_message

File "/app/fdi/fdi_venv/lib/python3.12/site-packages/pydantic_ai/models/openai.py", line 408 in _map_user_prompt

[2025-05-21, 23:51:34] INFO - Task instance in failure state: chan="stdout": source="task"
[2025-05-21, 23:51:34] INFO - Task start: chan="stdout": source="task"
[2025-05-21, 23:51:34] INFO - Task:<Task(AgentDecoratedOperator): classify>: chan="stdout": source="task"
[2025-05-21, 23:51:34] INFO - Failure caused by 'AgentRunResult' object is not iterable: chan="stdout": source="task"
