Log message source details: sources=["/app/fdi/airflow/logs/dag_id=document_classifier_dag/run_id=manual__2025-05-22T06:46:59.577501+00:00/task_id=classify/map_index=1/attempt=1.log"]
[2025-05-22, 12:16:59] INFO - DAG bundles loaded: dags-folder, example_dags: source="airflow.dag_processing.bundles.manager.DagBundlesManager"
[2025-05-22, 12:16:59] INFO - Filling up the DagBag from /app/fdi/dags/dynamic_input_agent.py: source="airflow.models.dagbag.DagBag"
[2025-05-22, 12:17:00] INFO - Running classifier for: https://hexawareonline.sharepoint.com/:b:/t/tensaiGPT-PROD-HR-Docs/ET0W0clrClhBrA7ZLzCoOmEBHq0vg-rFuGuEwb40Weq8zQ?e=6BkU3C: source="airflow.utils.log.logging_mixin.LoggingMixin"
[2025-05-22, 12:17:00] INFO - Task instance is in running state: chan="stdout": source="task"
[2025-05-22, 12:17:00] INFO -  Previous state of the Task instance: TaskInstanceState.QUEUED: chan="stdout": source="task"
[2025-05-22, 12:17:00] INFO - Current task name:classify: chan="stdout": source="task"
[2025-05-22, 12:17:00] INFO - Dag name:document_classifier_dag: chan="stdout": source="task"
[2025-05-22, 12:17:03] ERROR - Task failed with exception: source="task"
AttributeError: 'AgentRunResult' object has no attribute 'final_output'
File "/app/fdi/fdi_venv/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py", line 838 in run

File "/app/fdi/fdi_venv/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py", line 1130 in _execute_task

File "/app/fdi/fdi_venv/lib/python3.12/site-packages/airflow/sdk/bases/operator.py", line 408 in wrapper

File "/app/fdi/fdi_venv/lib/python3.12/site-packages/airflow/sdk/bases/decorator.py", line 251 in execute

File "/app/fdi/fdi_venv/lib/python3.12/site-packages/airflow/sdk/bases/operator.py", line 408 in wrapper

File "/app/fdi/fdi_venv/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py", line 216 in execute

File "/app/fdi/fdi_venv/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py", line 239 in execute_callable

File "/app/fdi/fdi_venv/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py", line 81 in run

File "/app/fdi/dags/dynamic_input_agent.py", line 87 in classify

[2025-05-22, 12:17:03] INFO - Task instance in failure state: chan="stdout": source="task"
[2025-05-22, 12:17:03] INFO - Task start: chan="stdout": source="task"
[2025-05-22, 12:17:03] INFO - Task:<Task(_PythonDecoratedOperator): classify>: chan="stdout": source="task"
[2025-05-22, 12:17:03] INFO - Failure caused by 'AgentRunResult' object has no attribute 'final_output': chan="stdout": source="task"
